### PR TITLE
move constructor try

### PR DESCRIPTION
**Pull request by digitalist**
had to implement move constructor, didn't work with =default:
gcc:

```
22: error: invalid application of ‘sizeof’ to incomplete type ‘sqlpp::mysql::detail::connection_handle_t’
  static_assert(sizeof(_Tp)>0,
```

this code doesn't crash with this patch, though:
`connections.emplace(config, sqlpp::mysql::connection(config));`

### CODE REVIEW

**Comment by rbock** [comment]
Right, admittedly I never know from the top of my head which operations are allowed for unique_ptr with just the forward declaration...

One issue is left: You need to copy the `_transaction_active` flag.

**Comment by digitalist** [comment]
I've added transaction flag handling and a test-case: 
- emplace new connection into a vector,
- do some sql setup
- start transaction
- move connection from vector into a variable
- assert transaction flag (added  `bool is_transaction_active()`)

**Comment by rbock** [comment]
Nice! Thanks :-)

**Comment by digitalist** [comment]
that's my first relatively big commit with c++ ever, yahoo.

**Comment by rbock** [comment]
Congrats! BTW, maybe you want to add yourself in the copyright notice at the top of the file?

**Comment by digitalist** [comment]
with a next patch, maybe ) thanks 

I guess similar changes must be added to postrges connector? API should be  consistent between drivers, so is_transaction_active() should go there too

**Comment by rbock** [comment]
I don't know much about the postgres connector. But yes, there should be a move constructor.

Same for MySQL/MariaDB

**Comment by digitalist** [comment]
(note to myself) mysql/percona/maria and other forks should use same connector, as long as they share same api/abi/drop-in replacement for one another.
postgres, firedb and any other rdbms including mysql family mentioned above should be as much compatible as possible

**Pull request merged**
