### PR TITLE
Fixed issue with thread_local for clang/llvm/libc++ for Apple's XCode

### PR DESCRIPTION
**Pull request by CapSel**
Fixed issue with thread_local for clang/llvm/libc++ for Apple's XCode… and rest of the world.
thread_local is not available on OSX and iOS.
Without CMakeLists.txt patches I was not able to link against boost.thread.

### CODE REVIEW

**Comment by CapSel** [comment]
AppVeyor failed. How can I fix it?

**Comment by rbock** [comment]
Thanks!

You can't really fix the AppVeyor build just now. That is due to regression in MSVC which is going to be fixed with the next major release, see also https://github.com/rbock/sqlpp11/issues/181

**Comment by rbock** [comment]
Should have looked at the log first...

That error is due to some misconfiguration, but once that's solved, we will run into the compile error almost certainly.

**Comment by rbock** [comment]
If you feel like it, you could take a look at this https://github.com/rbock/sqlpp11-connector-sqlite3/pull/39 and port that to the mysql connector

**Pull request merged**
